/**
A CSS property name, for ``Style/declaration(_:_:)``.

The properties without a typed modifier are static members, so they autocomplete, and a misspelled name does not compile. Add a static member for a new property. `Property("…")` is the escape hatch, which stands out in a review. Use a ``StyleVariable`` for a custom property:

```swift
Style()
	.declaration(.hyphens, "auto")
	.declaration(.webkitTextStroke, "1px")
```
*/
public struct Property: Hashable, Sendable, CustomStringConvertible {
	public let description: String

	public init(_ name: String) {
		self.description = name
	}
}

extension Property {
	public static let accentColor = Self("accent-color")
	public static let alignContent = Self("align-content")
	public static let alignItems = Self("align-items")
	public static let alignSelf = Self("align-self")
	public static let anchorName = Self("anchor-name")
	public static let animation = Self("animation")
	public static let animationDelay = Self("animation-delay")
	public static let animationRange = Self("animation-range")
	public static let animationTimeline = Self("animation-timeline")
	public static let appearance = Self("appearance")
	public static let aspectRatio = Self("aspect-ratio")
	public static let backdropFilter = Self("backdrop-filter")
	public static let background = Self("background")
	public static let backgroundClip = Self("background-clip")
	public static let backgroundColor = Self("background-color")
	public static let backgroundImage = Self("background-image")
	public static let backgroundPosition = Self("background-position")
	public static let backgroundSize = Self("background-size")
	public static let border = Self("border")
	public static let borderBottomColor = Self("border-bottom-color")
	public static let borderBottomWidth = Self("border-bottom-width")
	public static let borderCollapse = Self("border-collapse")
	public static let borderColor = Self("border-color")
	public static let borderRadius = Self("border-radius")
	public static let borderStyle = Self("border-style")
	public static let borderTopWidth = Self("border-top-width")
	public static let bottom = Self("bottom")
	public static let boxShadow = Self("box-shadow")
	public static let boxSizing = Self("box-sizing")
	public static let breakInside = Self("break-inside")
	public static let clipPath = Self("clip-path")
	public static let color = Self("color")
	public static let colorScheme = Self("color-scheme")
	public static let columnGap = Self("column-gap")
	public static let columns = Self("columns")
	public static let containerType = Self("container-type")
	public static let content = Self("content")
	public static let contentVisibility = Self("content-visibility")
	public static let counterIncrement = Self("counter-increment")
	public static let counterReset = Self("counter-reset")
	public static let cursor = Self("cursor")
	public static let direction = Self("direction")
	public static let display = Self("display")
	public static let fieldSizing = Self("field-sizing")
	public static let fill = Self("fill")
	public static let filter = Self("filter")
	public static let flex = Self("flex")
	public static let flexDirection = Self("flex-direction")
	public static let flexShrink = Self("flex-shrink")
	public static let flexWrap = Self("flex-wrap")
	public static let float = Self("float")
	public static let font = Self("font")
	public static let fontFamily = Self("font-family")
	public static let fontSize = Self("font-size")
	public static let fontStretch = Self("font-stretch")
	public static let fontStyle = Self("font-style")
	public static let fontVariantNumeric = Self("font-variant-numeric")
	public static let fontWeight = Self("font-weight")
	public static let gap = Self("gap")
	public static let gridArea = Self("grid-area")
	public static let gridAutoColumns = Self("grid-auto-columns")
	public static let gridAutoFlow = Self("grid-auto-flow")
	public static let gridColumn = Self("grid-column")
	public static let gridTemplateColumns = Self("grid-template-columns")
	public static let gridTemplateRows = Self("grid-template-rows")
	public static let hangingPunctuation = Self("hanging-punctuation")
	public static let height = Self("height")
	public static let hyphens = Self("hyphens")
	public static let imageRendering = Self("image-rendering")
	public static let inset = Self("inset")
	public static let insetInlineEnd = Self("inset-inline-end")
	public static let insetInlineStart = Self("inset-inline-start")
	public static let interpolateSize = Self("interpolate-size")
	public static let isolation = Self("isolation")
	public static let justifySelf = Self("justify-self")
	public static let justifyContent = Self("justify-content")
	public static let letterSpacing = Self("letter-spacing")
	public static let lineHeight = Self("line-height")
	public static let listStyle = Self("list-style")
	public static let listStyleType = Self("list-style-type")
	public static let margin = Self("margin")
	public static let maskImage = Self("mask-image")
	public static let maxHeight = Self("max-height")
	public static let maxWidth = Self("max-width")
	public static let minHeight = Self("min-height")
	public static let minWidth = Self("min-width")
	public static let mixBlendMode = Self("mix-blend-mode")
	public static let mozOSXFontSmoothing = Self("-moz-osx-font-smoothing")
	public static let objectFit = Self("object-fit")
	public static let opacity = Self("opacity")
	public static let order = Self("order")
	public static let outline = Self("outline")
	public static let outlineColor = Self("outline-color")
	public static let outlineOffset = Self("outline-offset")
	public static let overflow = Self("overflow")
	public static let overflowWrap = Self("overflow-wrap")
	public static let overflowX = Self("overflow-x")
	public static let overlay = Self("overlay")
	public static let overscrollBehaviorX = Self("overscroll-behavior-x")
	public static let padding = Self("padding")
	public static let paintOrder = Self("paint-order")
	public static let perspective = Self("perspective")
	public static let pointerEvents = Self("pointer-events")
	public static let position = Self("position")
	public static let positionAnchor = Self("position-anchor")
	public static let positionArea = Self("position-area")
	public static let positionTryFallbacks = Self("position-try-fallbacks")
	public static let quotes = Self("quotes")
	public static let rotate = Self("rotate")
	public static let rowGap = Self("row-gap")
	public static let scale = Self("scale")
	public static let scrollbarColor = Self("scrollbar-color")
	public static let scrollbarGutter = Self("scrollbar-gutter")
	public static let scrollbarWidth = Self("scrollbar-width")
	public static let scrollBehavior = Self("scroll-behavior")
	public static let scrollMarginTop = Self("scroll-margin-top")
	public static let scrollMarginBottom = Self("scroll-margin-bottom")
	public static let scrollPaddingTop = Self("scroll-padding-top")
	public static let scrollPaddingBottom = Self("scroll-padding-bottom")
	public static let scrollSnapAlign = Self("scroll-snap-align")
	public static let scrollSnapType = Self("scroll-snap-type")
	public static let strokeWidth = Self("stroke-width")
	public static let tabSize = Self("tab-size")
	public static let tableLayout = Self("table-layout")
	public static let textAlign = Self("text-align")
	public static let textBox = Self("text-box")
	public static let textDecoration = Self("text-decoration")
	public static let textDecorationColor = Self("text-decoration-color")
	public static let textDecorationThickness = Self("text-decoration-thickness")
	public static let textOverflow = Self("text-overflow")
	public static let textRendering = Self("text-rendering")
	public static let textShadow = Self("text-shadow")
	public static let textTransform = Self("text-transform")
	public static let textUnderlineOffset = Self("text-underline-offset")
	public static let textWrap = Self("text-wrap")
	public static let timelineScope = Self("timeline-scope")
	public static let top = Self("top")
	public static let touchAction = Self("touch-action")
	public static let transform = Self("transform")
	public static let transformOrigin = Self("transform-origin")
	public static let transformStyle = Self("transform-style")
	public static let transition = Self("transition")
	public static let translate = Self("translate")
	public static let userSelect = Self("user-select")
	public static let verticalAlign = Self("vertical-align")
	public static let viewTimelineName = Self("view-timeline-name")
	public static let viewTransitionClass = Self("view-transition-class")
	public static let viewTransitionName = Self("view-transition-name")
	public static let visibility = Self("visibility")
	public static let webkitBackdropFilter = Self("-webkit-backdrop-filter")
	public static let webkitFontSmoothing = Self("-webkit-font-smoothing")
	public static let webkitTapHighlightColor = Self("-webkit-tap-highlight-color")
	public static let webkitTextSizeAdjust = Self("-webkit-text-size-adjust")
	public static let webkitTextStroke = Self("-webkit-text-stroke")
	public static let whiteSpace = Self("white-space")
	public static let width = Self("width")
	public static let willChange = Self("will-change")
	public static let writingMode = Self("writing-mode")
	public static let zIndex = Self("z-index")
	public static let zoom = Self("zoom")
}
